(source gnu)
(source melpa)
(source marmalade)
(source org)
(source SC)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "powerline")
(depends-on "ido") 
(depends-on "smartparens") 
(depends-on "auto-complete") 
(depends-on "fill-column-indicator") 
(depends-on "highlight-indentation") 
(depends-on "flyspell") 
(depends-on "flymake") 
(depends-on "projectile")
(depends-on "markdown-mode")

(depends-on "virtualenvwrapper")
(depends-on "enh-ruby-mode")
(depends-on "rvm")
(depends-on "rinari")
(depends-on "rspec-mode")

(depends-on "js2-mode")
(depends-on "ess")
(depends-on "feature-mode")

(depends-on "polymode")
(depends-on "auctex")
(depends-on "org")

(depends-on "octave")


